export const GET_TOP_SALES = 'GET_TOP_SALES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATALOG_ITEMS = 'GET_CATALOG_ITEMS';
export const GET_CATALOG_ITEMS_MORE = 'GET_CATALOG_ITEMS_MORE';
export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const SEND_ORDER = 'SEND_ORDER';
